Fullpipe\ImageBundle\Entity\Image:
    type: mappedSuperclass
    table: fp_image
    fields:
        originalName:
            type: string
            length: 255
            nullable: true
            column: original_name
        path:
            type: string
            length: 255
        thumbSizes:
            type: array
            column: thumb_sizes
            nullable: true
    lifecycleCallbacks: {  }
